### ISSUE TITLE
new message turbo-frame tag collapsed to nil

### ISSUE THREAD

**Issue by dvodvo** [hotwired/hotwire-rails-demo-chat#10]
In attempting to reproduce the steps of the introductory video, the new message frame is not rendering.

new message view
```
<h1>New Message</h1>

<%= turbo_frame_tag 'new_message', target: '_top' do %>
  <%= form_with(model: [ @message.room, @message ]) do |form| %>
    <div class="field" style='min-height: 25px;'>
      <%= form.text_field :content %>
      <%= form.submit "Send" %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', @message.room %>
```
show room view
```
<%= turbo_frame_tag 'new message', src: new_room_message_path(@room), target: '_top' %>
```
Upon loading the page, the inspector shows the id='room' frame and its contents
but not that of the new_message
![Screen Shot 2021-01-24 at 10 54 36](https://user-images.githubusercontent.com/716130/105626823-cfa4ec80-5e32-11eb-8c1a-1119f1fb452a.png)
However the network tab does show the frame arriving
![Screen Shot 2021-01-24 at 10 57 02](https://user-images.githubusercontent.com/716130/105626858-0d097a00-5e33-11eb-92f4-b7a6f7ae438f.png)
and its content is that of the new message form.
![Screen Shot 2021-01-24 at 10 57 21](https://user-images.githubusercontent.com/716130/105626865-1d215980-5e33-11eb-9cb0-c7b965abe218.png)

I am suspecting a CSS style is one component of the collapse, as the margins or padding within the blue box of the room tag are present in the video, but not in localhost render.
![Screen Shot 2021-01-24 at 11 02 06](https://user-images.githubusercontent.com/716130/105626939-c36d5f00-5e33-11eb-8a27-c9869d26a7b4.png)
  I fail to find the element(s) required to generate the proper rendering.    

But that may not be a full explanation, as upon page load one frame is populated, but not the other,

**Comment by casi** [comment]
@dvodvo : I think you forgot the underscore to name the turbo frame id properly.

Maybe you try it like this: 
```<%= turbo_frame_tag 'new_message', src: new_room_message_path(@room), target: '_top' %>```

That could be it. I haven't noticed anything else yet.

**Comment by dvodvo** [comment]
That was *exactly* it.  I misintepreted the quotes as simple strings, when they imply the *string for the ID* of the DOM

**Comment by casi** [comment]
My pleasure. Glad, that i could help. :)
