### ISSUE TITLE
Destroy with link_to doesn't work, button_to does but data-confirm?

### ISSUE THREAD

**Issue by jillisstada** [hotwired/hotwire-rails-demo-chat#16]
Note that the helpers that turn `link_to` into remote invocations will _not_ currently work with Turbo. Links that have been made remote will not stick within frames nor will they allow you to respond with turbo stream actions. The recommendation is to replace these links with styled `button_to`, so you'll flow through a regular form, and you'll be better off with a11y compliance.

You can still use the `data-confirm` and `data-disable-with`.

**Comment by charlietag** [comment]
Hi @jillisstada , 

## Base on my understanding
if you do the following (which is hotwired/hotwire-rails-demo-chat doing)
`rails new new_project --skip-javascript`
`rails hotwire:install`

## This will only load hotwire related stuffs, not including rails-ujs, we have to add it back.

**vi app/assets/javascripts/application.js**
`//= require rails-ujs`

**vi app/views/layouts/application.html.erb**
```diff
    <%= stylesheet_link_tag 'application', media: 'all' %>
+   <%= javascript_include_tag 'application', 'data-turbo-track' => true %>
    <%= stimulus_include_tags %>
```

## And about this: https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md
I think this is for people who is using `data-remote=true`

**Comment by jillisstada** [comment]
that works, thank you

**Comment by nekketsuuu** [comment]
FYI: Now, turbo v7.0.0 offers `data-turbo-method`, which can be used to request a delete action with turbo stream, and turbo v7.1.0 offers `data-turbo-confirm`, which can be used to show a confirmation dialog without rails-ujs.

- https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.6
- https://github.com/hotwired/turbo/releases/tag/v7.1.0-rc.1
