### ISSUE TITLE
Newly created room is not connected to cable

### ISSUE THREAD

**Issue by vfonic** [hotwired/hotwire-rails-demo-chat#4]
Repro steps:

1. Run the app `rails s`
2. Create new room: http://localhost:3000/rooms/new
3.a In the new room view, click "Back"

or

3.b Post a new message using input box

### Expected

3.a User is redirected to rooms index without errors

### Actual

3.a User is redirected, but there's a new error thrown in the browser console (`Uncaught TypeError: this.subscription.unsubscribe is not a function`)

### Expected

3.b New message is posted and input box is cleared

### Actual

3.b New message is posted, but the input box is not cleared

Seems like stimulus controller is not wired correctly.

**Comment by dhh** [comment]
Can't replicate 3a in Chrome or Firefox. What browser/version are you using? Can replicate input box not clearing in chrome. Someone please do look into that.

**Comment by vfonic** [comment]
@dhh sorry, for 3.a user _is_ redirected, but there's an error thrown in the console. I tested in Brave, Firefox and Chrome.

**Comment by wildeng** [comment]
I've tried the suggested steps and I get the same error on the browser console, but only when I hit the back button. Sending a message in a newly created room works as expected. 
Tested on Firefox and Safari

I've recorded a brief screencast to show it

https://user-images.githubusercontent.com/661527/103177734-ed535600-4874-11eb-926c-edda8abb1771.mov

**Comment by codergeek121** [comment]
I think the unsubscription error has been fixed in this MR: https://github.com/hotwired/turbo-rails/pull/24/files
Pointing `turbo-rails` to the latest main commit, fixes it.

**Comment by wildeng** [comment]
yes, you're right. I've seen the fix. I guess that @vfonic could close this one

**Comment by dhh** [comment]
Pushed new Gemfile.lock with new dependencies that fixes this.
