### ISSUE TITLE
Where to put and how to manage JS libraries

### ISSUE THREAD

**Issue by varyform** [hotwired/hotwire-rails-demo-chat#8]
Hi, 

I have a question regarding "extra JS libraries" mentioned in the hotwire intro video.
Say I want to use Highcharts or head jQuery (which is ESM compatible) and still have them managed by Yarn.
What's the current/correct/suggested way to do it using import maps approach? 

Thanks!

**Comment by dhh** [comment]
If you want to manage things with yarn, stick to using the Webpack approach. If you want to use ESM, you have to get the dist files and placed them in app/assets/javascripts/libraries and they’ll be included in the import map 👍
